DATA_DIR = 'data'
LOG_DIR = 'logs'
TRAIN_DIR = f'{DATA_DIR}/AMASS/CMU'
VALID_DIR = f'{DATA_DIR}/AMASS/CMU_valid'
TEST_DIR = f'{DATA_DIR}/AMASS/CMU_test'
BATCH_SIZE = 10
FRAMES_PER_SAMPLE = 128
MASK_TEMPORAL_WINDOW = 25
